[gcp_service_account]
type = "service_account"
project_id = "goseisanshin"
private_key_id = "8b5f92a5b503c803e6afeec47988549e8081dc20"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbepjkZ5FmhuVs
gdqq3/Brd14AIccPs/YSIliDGJ/3HeFCiPU4BOLDY4jGDuNxlNG/8Z2gfQZpL2r6
ylgpZRaiVeayfF9/47/aYTSBGo4V1Ndpdl+4DehOcTOumn74xG9HMJYWLj1APO7P
MLat9Yz6W2ql8BivJQBGP0wVjBb7GOxgJAZH+MA1hvqDPDuGAXBOrxL+wnB9cQoL
Xr8y/fyV0Le7lFRS8HpiJffJkbIlP+1+gNmzJWPmY5KzaDWXzVg98g0HUweqSjne
hOcu8Xc9Jxrp7+dgHXJjahpOmAF8G4JHPgPa2Q8JAI3ZXUQyoZO0bW93eIjijZ97
3Ip54GT5AgMBAAECggEACG3EpuI9+c/PlXqzMO8HvL25gvqRzPZBvXEu+PlvZ6FP
LlEYMSejpvnJBwq01hoeJmCZ/eK1Q6PKUgsA7UqRh+6t/WhccYWWZ6d8JhEbWY/i
tzEPhp37ZXBB3+H4hvI4QaTeyBhM4gQDosgWaTceA88LqLAL2IfiHEzPaj4gW0+k
k5soYmLnaZaapi8w1MTTWsd390q6WUshsI9OPLO/kieE35SgaQlWACIsVfeNAwMy
IM1xBUZ+co+gxBXlFxFEGlCtJoLSSXegPIt5CG8ORy2S6foXZ/jV2yQC+oYyNUsa
7c3x5KaZk+AwIHDcbf0G6XiB3DKgchQWDkKN4D+fAQKBgQDKggtPjoI6bhEFcLkt
z290+iTBmWSQ82If9Tv34wv+Tv7Xkv5Zfl4AvMdQING7hRNhKgUDlYyninhD3oNY
+JbzitS9/Y0uqrpSu4ozsUyJUmmWZFjKRqPoOPCaNak5kiQbELRUQnM398w+mVAF
cOMCz8LDxgy+ZxOaZfML7uWF+QKBgQDEjFxtcSmntVHlIKVng4bHBS9pqyMoJDhK
9W66vP3V5a8iahCyrufya5QjsxkKxPFautBZ0LavcHnqeLmUnYeRfA3K4tRaqEGu
ptnERvUn1O/AO7K8pnVrAQ/Z5HuMn3wVjhMtqA1XR9ahOIFDDg2UqtAY2X5DNmtW
kCdAyd2XAQKBgE8GtrFCNLHml//egHVPGPi2UTe3y5YBVI6SHefbk6eXXj30IAv+
k2KISOONGyupf+mQA0rlxnDvSYV6xRkoUYgS6niGBN1sRK/afdE0ZGDGZ2wIFtpA
/N+3sLUNMc/EpxBk0Wp8UAhMTEk1fRPSfNRxDVlm5Tw8b1r2ZAWJIcrJAoGBAKXi
EOANciqpTcUkGHWU/FtcdPeqCLIIX7pkCmBwwYuVnopdGlq0Y+6l/RFkRu5f6ZO5
t78V+Bl5xGuwGHDlw1V2be2eI7uf5k+RYpnViXNktDR6LhAqLU9yRf6QZ/X3ZLKM
hoMyIpBXgT3wgqglZDDlOVy/s2DmvREB+R8lQHABAoGAMmrAuA7tv94p4pifO39r
bhjFnB/xBq4Xy+NNzpO+YZrBT37QGWb4TTq2wJERbGGnTGh79Y4dhVU06kzAF7oD
vwmTf2UH2oAENU9hmMP6rJdIV5TRTCjnCNk+LTsQjLu+1rS3V2c0fuyzUkskC9zY
o0YCYPUy2rYhKo8cBm1pyFU=
-----END PRIVATE KEY-----"""
client_email = "id-883@goseisanshin.iam.gserviceaccount.com"
client_id = "109464370345698300390"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/id-883%40goseisanshin.iam.gserviceaccount.com"
universe_domain = "googleapis.com"